svn move UfrmFIN_PlanoContas2.*                              Cadastros
svn move UdtmFIN_PlanoContas2.*                              Cadastros
svn move UfrmFIN_CentrosCusto.*                              Cadastros
svn move UdtmFIN_CentrosCusto.*                              Cadastros
svn move UfrmFIN_Contas2.*                                   Cadastros
svn move UdtmFIN_Contas2.*                                   Cadastros
svn move UfrmFIN_Bancos.*                                    Cadastros
svn move UdtmFIN_Bancos.*                                    Cadastros
svn move UFin_CadastroPatrimonioWizard.*                     Cadastros
svn move UFin_CadastroPatrimonioDatamodule.*                 Cadastros
svn move qReport\UFin_PlanoContasRelatorio.*                 Cadastros\Report
svn move qReport\UFin_CentroCustosRelatorio.*                Cadastros\Report
svn move qReport\UCAD_PatrimonioReport.*                     Cadastros\Report
svn move qReport\UEST_ProdutosInsumosReport.*                Cadastros\Report
svn move qReport\UEST_ProdutosInsumosReportDialog.*          Cadastros\Report
svn move qReport\UEST_ServicosReport.*                       Cadastros\Report
svn move qReport\UFIN_InventarioProdutosReport.*             Cadastros\Report
svn move qReport\UFin_MovimentacaoContasDialog.*             Cadastros\Report
svn move qReport\UFin_MovimentacaoContasReport.*             Cadastros\Report
                pause
